baseURL = 'https://longnt258.github.io./exploit-s3-bucket'
languageCode = 'en-us'
title = 'Exploitation AWS S3 Bucket'
theme = 'hugo-theme'

[menu]
    [[menu.main]]
    name = "Introdution"
    identifier = "introdution"
    weight = 1
    url = "/introdution/"

        [[menu.main]]
        name = "Attack vector"
        identifier = "attack-vector"
        weight = 1
        url = "/introdution/attack-vector"

        [[menu.main]]
        name = "Attack surface"
        identifier = "attack-surface"
        weight = 2
        url = "/introdution/attack-surface"

        [[menu.main]]
        name = "The difference between On-Premise and On-Cloud"
        identifier = "premise-cloud"
        weight = 3
        url = "/introdution/premise-cloud"
        
    [[menu.main]]
    name = "Exploitation"
    identifier = "exploitation"
    weight = 2
    url = "/exploitation/"

        [[menu.main]]
        name = "Preparation"
        identifier = "preparation"
        weight = 1
        url = "/exploitation/preparation"

        [[menu.main]]
        name = "Implement"
        identifier = "implement"
        weight = 2
        url = "/exploitation/implement"

    [[menu.main]]
    name = "Solution"
    identifier = "solution"
    weight = 3
    url = "/solution/"

        [[menu.main]]
        name = "Solutions"
        identifier = "solutions"
        weight = 1
        url = "/solution/solutions"